# FraudShield Pipeline Tutorial

This notebook walks through the local pipeline from ingestion to batch training,
evaluation, and aligned online inference using the shared runtime settings.

In [1]:
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from fraudshield.config.settings import ModelArtifactSettings, get_settings  # noqa: E402
from fraudshield.data_ingestion.data_ingestion import DataIngestion  # noqa: E402
from fraudshield.data_preprocessing.data_preprocessing import preprocess_and_save  # noqa: E402
from fraudshield.ml.inference.service import FraudInferenceService  # noqa: E402
from fraudshield.model_evaluation.evaluation import evaluate_and_save  # noqa: E402
from fraudshield.model_training.train_models import train_and_save  # noqa: E402
from fraudshield.runtime.logging import configure_logging  # noqa: E402
from fraudshield.runtime.resources import load_inference_artifacts  # noqa: E402

settings = get_settings()
configure_logging(settings, component="notebook_pipeline")

raw_data_path = PROJECT_ROOT / "data" / "raw" / "synthetic_fraud_data.csv"
run_dir = PROJECT_ROOT / "data" / "models" / "notebook_pipeline"
run_dir.mkdir(parents=True, exist_ok=True)
raw_data_path

PosixPath('/Users/mudit/Developer/FraudShield/data/raw/synthetic_fraud_data.csv')

In [2]:
pd.Series(
    {
        "project_root": str(settings.project_root),
        "database_url": settings.database.sqlalchemy_url,
        "default_model": settings.models.default_model_name,
        "raw_data": str(raw_data_path),
        "run_dir": str(run_dir),
    },
    name="value",
).to_frame().rename_axis("setting")

                                                           value
setting
project_root                  /Users/mudit/Developer/FraudShield
database_url   sqlite:////Users/mudit/Developer/FraudShield/d...
default_model                                            xgboost
raw_data       /Users/mudit/Developer/FraudShield/data/raw/sy...
run_dir        /Users/mudit/Developer/FraudShield/data/models...

## 1. Load The Sample Dataset

The repository ships with a synthetic dataset that exercises the batch and
realtime components without requiring external infrastructure.

In [3]:
raw_df = pd.read_csv(raw_data_path, parse_dates=["transaction_date"])
raw_df.head()

,transaction_id,user_id,merchant_id,transaction_date,amount,currency,status,is_international,is_online,fraud
0,2215,24,20,2024-01-01 00:14:40,31.63,USD,approved,False,True,0
1,2084,134,44,2024-01-01 00:19:58,21.31,USD,approved,True,True,0
2,4932,147,1,2024-01-01 00:46:43,39.81,JPY,approved,True,True,1
3,4139,177,74,2024-01-01 00:57:57,23.15,USD,reversed,False,True,0
4,863,25,47,2024-01-01 01:49:23,60.21,GBP,declined,False,False,0

## 2. Ingest Into SQLite

We use the same ingestion class as the CLI entrypoint, but keep the notebook
run isolated in its own SQLite database.

In [4]:
sqlite_path = PROJECT_ROOT / "data" / "processed" / "notebook_pipeline.db"
ingestor = DataIngestion(str(raw_data_path.parent), f"sqlite:///{sqlite_path}")
try:
    ingestor.run_ingestion_pipeline(raw_data_path.name, "fraud_data", if_exists="replace", chunksize=500)
finally:
    ingestor.close()

sqlite_path

2026-06-15 19:23:56,475 INFO [fraudshield.data_ingestion.data_ingestion] Starting data ingestion pipeline for file: synthetic_fraud_data.csv
2026-06-15 19:23:56,483 INFO [fraudshield.data_ingestion.data_ingestion] Successfully read file: /Users/mudit/Developer/FraudShield/data/raw/synthetic_fraud_data.csv
2026-06-15 19:23:56,523 INFO [fraudshield.data_ingestion.data_ingestion] Data ingested successfully into table: fraud_data
2026-06-15 19:23:56,523 INFO [fraudshield.data_ingestion.data_ingestion] Data ingestion pipeline completed successfully for file: synthetic_fraud_data.csv

PosixPath('/Users/mudit/Developer/FraudShield/data/processed/notebook_pipeline.db')

## 3. Preprocess And Persist Aligned Artifacts

This step creates train/test arrays plus the preprocessor and metadata used by
the online inference service.

In [5]:
train_path = run_dir / "preprocessed_data.npy"
test_path = run_dir / "test_data.npy"
preprocessor_path = run_dir / "preprocessor.joblib"
metadata_path = run_dir / "preprocessing_metadata.json"

preprocess_and_save(
    input_data=str(raw_data_path),
    train_data=str(train_path),
    test_data=str(test_path),
    preprocessor_path=str(preprocessor_path),
    metadata_path=str(metadata_path),
    feature_windows=["1h", "24h", "7d"],
    id_columns=None,
)

metadata = json.loads(metadata_path.read_text())
{
    "feature_count": len(metadata["feature_names"]),
    "input_columns": metadata["input_feature_columns"][:8],
    "feature_windows": metadata["feature_windows"],
}

2026-06-15 19:23:58,889 INFO [fraudshield.data_preprocessing.data_preprocessing] Reading input data from: /Users/mudit/Developer/FraudShield/data/raw/synthetic_fraud_data.csv
2026-06-15 19:23:58,898 INFO [fraudshield.data_preprocessing.data_preprocessing] Starting data preprocessing...
2026-06-15 19:23:59,375 INFO [fraudshield.data_preprocessing.data_preprocessing] Applying C++ data cleaning routines for column: amount
2026-06-15 19:23:59,376 INFO [fraudshield.data_preprocessing.data_preprocessing] Using time-based split based on transaction date.
2026-06-15 19:23:59,379 INFO [fraudshield.data_preprocessing.data_preprocessing] Inferring numeric and categorical features...
2026-06-15 19:23:59,380 INFO [fraudshield.data_preprocessing.data_preprocessing] Building preprocessing pipeline...
2026-06-15 19:23:59,381 INFO [fraudshield.data_preprocessing.data_preprocessing] Fitting preprocessing pipeline on training data...
2026-06-15 19:23:59,403 INFO [fraudshield.data_preprocessing.data_preprocessing] Data preprocessing completed successfully!
2026-06-15 19:23:59,404 INFO [fraudshield.data_preprocessing.data_preprocessing] Saving preprocessed train data to: /Users/mudit/Developer/FraudShield/data/models/notebook_pipeline/preprocessed_data.npy
2026-06-15 19:23:59,406 INFO [fraudshield.data_preprocessing.data_preprocessing] Saving preprocessed test data to: /Users/mudit/Developer/FraudShield/data/models/notebook_pipeline/test_data.npy

{'feature_count': 37,
 'input_columns': ['amount',
  'currency',
  'status',
  'is_international',
  'is_online',
  'user_time_since_last_txn',
  'user_amount_zscore',
  'user_txn_count_1h'],
 'feature_windows': ['1h', '24h', '7d']}

In [6]:
train_matrix = np.load(train_path)
test_matrix = np.load(test_path)
{
    "train_shape": train_matrix.shape,
    "test_shape": test_matrix.shape,
}

{'train_shape': (4000, 38), 'test_shape': (1000, 38)}

### 2.5 Data Drift Check (Optional Airflow Task)

Before training, we can validate that the feature distributions between the training set and testing set have not significantly drifted using a Kolmogorov-Smirnov test. This is the exact check running in the Airflow DAG.

In [7]:
from fraudshield.data_pipeline.pipeline_tasks import run_data_drift_check

try:
    # We set a high threshold here so the tutorial proceeds even if synthetic data drifts
    run_data_drift_check(
        train_data=str(train_path),
        test_data=str(test_path),
        metadata_path=str(metadata_path),
        max_drift_ratio=1.0
    )
except Exception as e:
    print(f"Drift Exception: {e}")

2026-06-15 19:24:01,425 INFO [fraudshield.data_pipeline.pipeline_tasks] Starting data drift check
2026-06-15 19:24:01,433 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__amount: KS stat=0.0545, p_value=1.6869e-02
2026-06-15 19:24:01,444 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__user_time_since_last_txn: KS stat=0.0828, p_value=3.3403e-05
2026-06-15 19:24:01,453 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__user_amount_zscore: KS stat=0.1217, p_value=8.9973e-11
2026-06-15 19:24:01,469 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__user_amount_sum_7d: KS stat=0.0525, p_value=2.3782e-02
2026-06-15 19:24:01,481 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__merchant_amount_mean_24h: KS stat=0.0840, p_value=2.3900e-05
2026-06-15 19:24:01,488 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__merchant_txn_count_7d: KS stat=0.0650, p_value=2.2514e-03
2026-06-15 19:24:01,491 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__merchant_amount_mean_7d: KS stat=0.0490, p_value=4.2061e-02
2026-06-15 19:24:01,497 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__merchant_fraud_rate_7d: KS stat=0.1013, p_value=1.4071e-07
2026-06-15 19:24:01,503 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__currency_txn_count_24h: KS stat=0.0732, p_value=3.6082e-04
2026-06-15 19:24:01,517 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__currency_txn_count_7d: KS stat=0.2512, p_value=7.4722e-45
2026-06-15 19:24:01,587 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__status_txn_count_24h: KS stat=0.1845, p_value=2.9493e-24
2026-06-15 19:24:01,609 WARNING [fraudshield.data_pipeline.pipeline_tasks] Drift detected in num__status_txn_count_7d: KS stat=0.3187, p_value=1.8317e-72
2026-06-15 19:24:01,620 INFO [fraudshield.data_pipeline.pipeline_tasks] Data drift check completed: 12/37 (32.4%) features drifted.

## 4. Train And Evaluate

The notebook keeps artifacts in a notebook-specific directory so the canonical
repo outputs remain untouched.

In [8]:
metrics = train_and_save(
    preprocessed_data=str(train_path),
    test_data=str(test_path),
    output_dir=str(run_dir),
    model="xgb",
)
pd.DataFrame(metrics).T

2026-06-15 19:24:06,804 INFO [fraudshield.model_training.train_models] XGBoost Metrics:
2026-06-15 19:24:06,805 INFO [fraudshield.model_training.train_models] {'accuracy': 0.911, 'precision': 0.2608695652173913, 'recall': 0.07692307692307693, 'f1_score': 0.1188118811881188, 'roc_auc': 0.6714083096946437, 'average_precision': 0.17607154291293953}
2026-06-15 19:24:06,808 INFO [fraudshield.model_training.train_models] Model saved to: /Users/mudit/Developer/FraudShield/data/models/notebook_pipeline/xgboost.pkl

         accuracy  precision    recall  f1_score   roc_auc  average_precision
xgboost     0.911    0.26087  0.076923  0.118812  0.671408           0.176072

In [9]:
report_path = run_dir / "evaluation_report.csv"
confusion_path = run_dir / "confusion_matrix.png"
_ = evaluate_and_save(
    model_path=str(run_dir / "xgboost.pkl"),
    test_data=str(test_path),
    output_path=str(report_path),
    confusion_matrix_path=str(confusion_path),
    normalize_cm=True,
)
pd.read_csv(report_path)

              Metric     Value
0           Accuracy  0.911000
1          Precision  0.260870
2             Recall  0.076923
3           F1 Score  0.118812
4            ROC AUC  0.671408
5  Average Precision  0.176072

## 5. Score A Realtime Event With The Same Artifacts

This is the important alignment check: the inference layer reloads the trained
model, preprocessor, and feature metadata together.

In [10]:
artifact_settings = ModelArtifactSettings(
    model_dir=run_dir,
    default_model_name="xgboost",
    preprocessor_path=preprocessor_path,
    metadata_path=metadata_path,
)
service = FraudInferenceService(
    settings=settings,
    model_name="xgboost",
    artifacts=load_inference_artifacts(artifact_settings, "xgboost"),
)

sample_event = raw_df.iloc[-1].to_dict()
prediction = service.predict(sample_event)
{
    "transaction_id": prediction.transaction_id,
    "fraud_probability": round(prediction.fraud_probability, 4),
    "source": prediction.source,
    "model_loaded": prediction.model_loaded,
}

2026-06-15 19:24:09,612 INFO [fraudshield.ml.explainability.shap_explainer] XGBoost model detected, using native pred_contribs for explanations.

{'transaction_id': 401,
 'fraud_probability': 0.002,
 'source': 'trained_model',
 'model_loaded': True}

## Next Steps

- Switch the SQLite target to PostgreSQL by setting `FRAUDSHIELD_DATABASE_URL`.
- Replace the synthetic CSV with a warehouse extract or feature store snapshot.
- Reuse the generated artifacts in the FastAPI service by pointing the model paths
  at the desired output directory.